data_paths:
  raw_data: "data/raw/telco-customer-dataset.xls"
  processed_data: "processed/telco-customer-dataset_missing_values_handled.csv"
  artifacts_dir: "artifacts"
  data_artifacts_dir: "artifacts/data"
  model_artifacts_dir: "artifacts/models"
  X_train: "artifacts/data/X_train.csv"
  X_test: "artifacts/data/X_test.csv"
  Y_train: "artifacts/data/Y_train.csv"
  Y_test: "artifacts/data/Y_test.csv"

columns:
  target: "Churn"
  new_column: "HasInternet"
  old_column: "InternetService"
  fill_columns: ["Partner", "Dependents", "PhoneService", "PaperlessBilling", "Churn"]
  internet_columns: ['OnlineSecurity', 'OnlineBackup', 'DeviceProtection','TechSupport', 'StreamingTV', 'StreamingMovies']
  phone_columns: ['MultipleLines']
  critical_columns: ["TotalCharges"]
  outlier_columns: ['tenure', 'MonthlyCharges', 'TotalCharges']
  nominal_columns: ['gender', 'InternetService', 'Contract', 'PaymentMethod']
  numeric_columns: ['MonthlyCharges','TotalCharges']
  feature_columns: []



outlier_detection:
  detection_method: "iqr"
  handling_method: "remove"
  z_score_threshold: 3.0

feature_binning:
  tenure_bins:
    New: [0, 6]
    Early: [6, 12]
    Established: [12, 24]
    Mature: [24, 48]
    Loyal: [48]
  tenure_mapping:
    New: 0
    Early: 1
    Established: 2
    Mature: 3
    Loyal: 4

feature_encoding:
  nominal_columns: ['gender', 'InternetService', 'Contract', 'PaymentMethod']
  ordinal_mappings:
    tenureBins:
      New: 0
      Early: 1
      Established: 2
      Mature: 3
      Loyal: 4

feature_scaling:
  scaling_type: "minmax"
  columns_to_scale: ['MonthlyCharges','TotalCharges']

data_splitting:
  split_type: "simple"
  test_size: 0.2
  random_state: 42
  n_splits: 5

training:
  default_model_type: "random_forest"
  default_training_strategy: "cv"
  cv_folds: 5
  random_state: 42
  test_size: 0.2
  validation_split: 0.2
  early_stopping_patience: 10
  max_iterations: 1000
  hyperparameter_tuning:
    enabled: false
    search_method: "grid"
    cv_folds: 5
    n_iter: 20

model:
  model_type: "random_forest"
  training_strategy: "cv"
  data_path: "data/raw/ChurnModelling.csv"
  model_path: "artifacts/models/random_forest_cv_model.pkl"
  evaluation_path: "artifacts/evaluation/random_forest_cv_evaluation_report.txt"
  model_params:
    n_estimators: 100
    max_depth: 10
    random_state: 42
  model_types:
    random_forest:
      n_estimators: 100
      max_depth: 10
      random_state: 42
    gradient_boosting:
      n_estimators: 100
      max_depth: 5
      random_state: 42
    logistic_regression:
      random_state: 42
      max_iter: 1000
    svm:
      random_state: 42
      probability: true

evaluation:
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1-score"
  cv_folds: 5
  random_state: 42

deployment:
  model_name: "churn_analysis_model"
  model_version: "1.0.0"
  api_endpoint: "/predict"
  batch_size: 1000

inference:
  model_name: "random_forest_cv_model"
  data_path: "artifacts/data/X_test.csv"
  sample_size: 100
  save_path: "artifacts/predictions/predictions.csv"
  batch_size: 1000
  return_proba: true

logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"
  file: "pipeline.log"

mlflow:
  tracking_uri: "file:./mlruns"  # Local file-based tracking
  experiment_name: "Telco Customer Churn Analysis"
  model_registry_name: "churn_prediction"
  artifact_path: "model"
  run_name_prefix: "churn_run"
  tags:
    project: "customer_churn_prediction"
    team: "ml_engineering"
    environment: "development"
  autolog: true


environment:
  experiment_name: "churn_analysis"

pipeline:
  data_pipeline_name: "data_processing_pipeline"
  training_pipeline_name: "model_training_pipeline"
  deployment_pipeline_name: "model_deployment_pipeline"
  inference_pipeline_name: "inference_pipeline"
  enable_cache: false